jwt:
  keystore:
    store-location: ${KEY_HOME}/jwt-keystore.jceks
    password: ${KEY_STORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    key-password: ${KEY_PASSWORD}

spring:

  application:
    name: monio

  datasource:
    url: jdbc:postgresql://${DB_LOCATION}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000

  data:
    redis:
      timeout: 2000ms  # Connection timeout
      connect-timeout: 2000ms  # Client connection timeout
      ssl:
        enabled: false  # Enable if using SSL
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  docker:
    compose:
      enabled: true

  flyway:
    enabled: true
    # Folder containing migration scripts
    locations: classpath:db/migration
    # Use if you are setting up Flyway in an existing database
    baseline-on-migrate: true
    # Allow migrations to be applied out of order if needed
    out-of-order: true
    # Define schemas for migrations if needed
    schemas: public



logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.smart_tiger.monio: INFO